context:
  version: "0.6.6"

package:
  name: lit-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@lit-labs/cli/-/cli-${{ version }}.tgz
  sha256: 68b3bcdd494e394a84a71e19baa53ee3db762f41083956d5391d202e6638f0d9

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - lit --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Tooling for Lit development
  homepage: https://github.com/lit/lit
  repository: https://github.com/lit/lit

extra:
  recipe-maintainers:
    - danielnachun
